WITH CANT_RENTAL AS (
    SELECT DISTINCT CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE 
    (START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01') OR 
    (START_DATE < '2022-11-01' AND END_DATE >= '2022-12-01')
),
DISCOUNT AS (
    SELECT CAR_TYPE, DISCOUNT_RATE 
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
)
SELECT C.CAR_ID, C.CAR_TYPE, 
       CONVERT((C.DAILY_FEE * 30) * (100 - D.DISCOUNT_RATE) / 100, UNSIGNED) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C 
JOIN DISCOUNT D ON C.CAR_TYPE = D.CAR_TYPE 
WHERE NOT EXISTS (
    SELECT 1 
    FROM CANT_RENTAL cr 
    WHERE cr.CAR_ID = C.CAR_ID
)
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;