SELECT FR.PRODUCT_ID, FR.PRODUCT_NAME, SUM(FR.PRICE * FO.AMOUNT) AS TOTAL_SALES 
FROM FOOD_PRODUCT FR 
JOIN FOOD_ORDER FO
ON FR.PRODUCT_ID = FO.PRODUCT_ID
WHERE MONTH(FO.PRODUCE_DATE) = 5 
GROUP BY FR.PRODUCT_ID, FR.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, FR.PRODUCT_ID ASC;