-- 코드를 입력하세요
SELECT BO.BOOK_ID, AU.AUTHOR_NAME, DATE_FORMAT(BO.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK BO
JOIN AUTHOR AU
ON BO.AUTHOR_ID = AU.AUTHOR_ID
WHERE BO.CATEGORY in ('경제')
ORDER BY BO.PUBLISHED_DATE ASC;